spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: 1234!


mybatis:
  mapper-locations: classpath:mapper/*.xml